"""
Structured AI response schemas.
"""

from pydantic import BaseModel, Field


class SummaryResponse(BaseModel):
    """
    Represents a structured summary generated by the AI model.
    """

    summary: str = Field(
        ...,
        description="Concise summary of the provided text.",
    )

    keywords: list[str] = Field(
        default_factory=list,
        description="List of important keywords extracted from the text.",
    )
